export const statisticsEvent = {
    parkSwitch: { eventid: "parkSwitch", eventLabel: "园区切换" },
    globalSearch: { eventid: "globalSearch", eventLabel: "全局搜索" },
    scan: { eventid: "scan", eventLabel: "扫一扫" },
    card: { eventid: "card", eventLabel: "一卡通" },
    access: { eventid: "access", eventLabel: "门禁卡" },

    contact: { eventid: "contact", eventLabel: "通讯录" },
    contactSearch: { eventid: "contactSearch", eventLabel: "通讯录搜索" },
    contactView: { eventid: "contactView", eventLabel: "通讯录查看" },
    contactSMS: { eventid: "contactSMS", eventLabel: "发短信" },
    contactPhoneCall: { eventid: "contactPhoneCall", eventLabel: "打电话" },
    contactEmail: { eventid: "contactEmail", eventLabel: "发邮件" },
    highFrequencyApplicationClicks: { eventid: "highFrequencyApplicationClicks", eventLabel: "高频应用点击次数" },
    parkSecretary: { eventid: "parkSecretary", eventLabel: "园区小秘书" },

    impressionView: { eventid: "impressionView", eventLabel: "印象查看" },
    seeImpression: { eventid: "seeImpression", eventLabel: "园区概况查看" },
    parkConsult: { eventid: "parkConsult", eventLabel: "园区咨询" },
    parkViewRoom: { eventid: "parkViewRoom", eventLabel: "预约看房" },
    parkCheckin: { eventid: "parkCheckin", eventLabel: "入驻申请" },
    ParkPhoneCall: { eventid: "ParkPhoneCall", eventLabel: "拨打电话" },
    parkSubmitViewRoom: { eventid: "parkSubmitViewRoom", eventLabel: "提交预约看房" },

    spaceView: { eventid: "spaceView", eventLabel: "空间列表查看" },
    spaceDetailView: { eventid: "spaceDetailView", eventLabel: "空间详情查看" },
    parkMeetingDetailView: { eventid: "parkMeetingDetailView", eventLabel: "会议室详情查看" },
    parkAdvertisingDetailView: { eventid: "parkAdvertisingDetailView", eventLabel: "广告位详情查看" },
    parkStationDetailView: { eventid: "parkStationDetailView", eventLabel: "工位详情查看" },
    parkSitemDetailView: { eventid: "parkSitemDetailView", eventLabel: "场地详情查看" },

    parkActiveList: { eventid: "parkActiveList", eventLabel: "活动列表" },
    parkActiveLatestRelease: { eventid: "parkActiveLatestRelease", eventLabel: "最新发布" },
    parkActiveHotClick: { eventid: "parkActiveHotClick", eventLabel: "热门点击" },
    parkActiveMostInvolved: { eventid: "parkActiveMostInvolved", eventLabel: "最多参与" },
    parkActivityTime: { eventid: "parkActivityTime", eventLabel: "活动时间" },
    parkActivityDetailView: { eventid: "parkActivityDetailView", eventLabel: "活动详情查看" },
    parkActivityEnrollment: { eventid: "parkActivityEnrollment", eventLabel: "活动报名" },

    parkCircleList: { eventid: "parkCircleList", eventLabel: "话题列表" },
    parkCircleDetailView: { eventid: "parkCircleDetailView", eventLabel: "话题详情查看" },
    parkPartakeCircle: { eventid: "parkPartakeCircle", eventLabel: "参与话题" },
    parkCancelPartakeCircle: { eventid: "parkCancelPartakeCircle", eventLabel: "取消参与话题" },
    parkCircleAdd: { eventid: "parkCircleAdd", eventLabel: "发布动态" },
    parkCircleDynamicView: { eventid: "parkCircleDynamicView", eventLabel: "查看全部动态" },
    parkCircleMyfollowDynamicView: { eventid: "parkCircleMyfollowDynamicView", eventLabel: "查看我关注的动态" },
    parkCirclefollowUser: { eventid: "parkCirclefollowUser", eventLabel: "关注用户" },
    parkCircleCancelfollowUser: { eventid: "parkCircleCancelfollowUser", eventLabel: "取消关注用户" },
    parkUserHomeView: { eventid: "parkUserHomeView", eventLabel: "查看用户主页" },
    parkCircleDynamicDetailView: { eventid: "parkCircleDynamicDetailView", eventLabel: "查看动态详情" },
    parkCircleSendComments: { eventid: "parkCircleSendComments", eventLabel: "动态发布评论" },
    parkCircleReplyComments: { eventid: "parkCircleReplyComments", eventLabel: "动态回复评论" },
    parkCircleDeleteComment: { eventid: "parkCircleDeleteCommefnt", eventLabel: "动态删除评论" },
    parkCircleDynamicPraise: { eventid: "parkCircleDynamicPraise", eventLabel: "动态点赞" },
    parkCircleDynamicfollow: { eventid: "parkCircleDynamicfollow", eventLabel: "动态收藏" },
    parkCircleDynamicshare: { eventid: "parkCircleDynamicshare", eventLabel: "动态分享" },

    parkPolicyListBrowse: { eventid: "parkPolicyListBrowse", eventLabel: "政策列表浏览" },
    parkPolicyDetailView: { eventid: "parkPolicyDetailView", eventLabel: "政策详情查看" },
    parkPolicyShare: { eventid: "parkPolicyShare", eventLabel: "政策分享" },
    parkPolicySearch: { eventid: "parkPolicySearch", eventLabel: "政策搜索" },
    policyMatchAgain: { eventid: "policyMatchAgain", eventLabel: "政策重新匹配" },
    policyMatchSkip: { eventid: "policyMatchSkip", eventLabel: "跳过匹配" },
    policyMatchConfirm: { eventid: "policyMatchConfirm", eventLabel: "确认匹配" },
    noticeListBrowse: { eventid: "noticeListBrowse", eventLabel: "通知公告列表" },
    noticeListDetailView: { eventid: "noticeListDetailView", eventLabel: "通知公告详情查看" },
    parkHeadlineListBrowse: { eventid: "parkHeadlineListBrowse", eventLabel: "资讯列表浏览" },
    parkHeadlineDetailView: { eventid: "parkHeadlineDetailView", eventLabel: "资讯详情查看" },
    customSetting: { eventid: "customSetting", eventLabel: "自定义设置" },
    visitorsAppointmentBrowse: { eventid: "visitorsAppointmentBrowse", eventLabel: "访客预约浏览" },
    submitVisitorsAppointmentAppli: { eventid: "submitVisitorsAppointmentAppli", eventLabel: "提交访客预约申请" },
    myVisitorListView: { eventid: "myVisitorListView", eventLabel: "查看我的访客单" },

    repairBrowse: { eventid: "repairBrowse", eventLabel: "物业报修浏览" },
    submitRepairApplication: { eventid: "submitRepairApplication", eventLabel: "提交物业报修申请" },
    myRepairApplicationView: { eventid: "myRepairApplicationView", eventLabel: "查看我的物业报修申请" },

    complainBrowse: { eventid: "complainBrowse", eventLabel: "物业投诉浏览" },
    submitComplainApplication: { eventid: "submitComplainApplication", eventLabel: "提交物业投诉申请" },

    parkingApplicationBrowse: { eventid: "parkingApplicationBrowse", eventLabel: "停车位申请浏览" },
    submitParkingApplication: { eventid: "submitParkingApplication", eventLabel: "提交停车位申请申请" },

    needApplicationBrowse: { eventid: "needApplicationBrowse", eventLabel: "需求提报浏览" },
    submitNeedApplication: { eventid: "submitNeedApplication", eventLabel: "提交需求提报申请" },

    checkinApplicationsBrowse: { eventid: "checkinApplicationsBrowse", eventLabel: "入驻申请浏览" },
    submitCheckinApplication: { eventid: "submitCheckinApplication", eventLabel: "提交入驻申请" },

    marketInBrowse: { eventid: "marketInBrowse", eventLabel: "服务机构入驻浏览" },
    submitMarketInApplication: { eventid: "submitMarketInApplication", eventLabel: "提交服务机构入驻申请" },

    parkConsultListBrowse: { eventid: "parkConsultListBrowse", eventLabel: "咨询列表浏览" },
    parkconsultBrowse: { eventid: "parkconsultBrowse", eventLabel: "园区咨询浏览" },
    sbmitParkconsultApplication: { eventid: "sbmitParkconsultApplication", eventLabel: "提交园区咨询申请" },
    myConsultView: { eventid: "myConsultView", eventLabel: "查看我的咨询" },

    invoiceView: { eventid: "invoiceView", eventLabel: "开票记录浏览" },
    invoiceRegisterView: { eventid: "invoiceRegisterView", eventLabel: "查看预登记发票" },
    invoiceStayView: { eventid: "invoiceStayView", eventLabel: "查看待开票发票" },
    invoiceAlreadyView: { eventid: "invoiceAlreadyView", eventLabel: "查看已开票发票" },
    invoiceCancelView: { eventid: "invoiceCancelView", eventLabel: "查看已取消发票" },
    invoiceDetailView: { eventid: "invoiceDetailView", eventLabel: "查看发票明细" },
    invoiceOrderView: { eventid: "invoiceOrderView", eventLabel: "查看发票订单明细" },
    invoiceRiseAdd: { eventid: "invoiceRiseAdd", eventLabel: "新增发票抬头" },
    invoiceRisePost: { eventid: "invoiceRisePost", eventLabel: "修改发票抬头" },
    invoiceRiseDelete: { eventid: "invoiceRiseDelete", eventLabel: "删除发票抬头" },

    couponNotUseView: { eventid: "couponNotUseView", eventLabel: "查看未使用优惠券" },
    couponAlreadyUseView: { eventid: "couponAlreadyUseView", eventLabel: "查看已使用优惠券" },
    couponExpireView: { eventid: "couponExpireView", eventLabel: "查看已过期优惠券" },
    couponStopUseView: { eventid: "couponStopUseView", eventLabel: "查看已停用优惠券" },
    couponGiveView: { eventid: "couponGiveView", eventLabel: "查看已转增优惠券" },
    couponGive: { eventid: "couponGive", eventLabel: "优惠券转赠" },
    couponUse: { eventid: "couponUse", eventLabel: "优惠券使用" },

    goToCouponView: { eventid: "goToCouponView", eventLabel: "去领券中心看看" },
    couponAllView: { eventid: "couponAllView", eventLabel: "查看全部优惠券" },
    couponCurrencyView: { eventid: "couponCurrencyView", eventLabel: "查看通用优惠券" },
    couponTemporaryParkingView: { eventid: "couponTemporaryParkingView", eventLabel: "查看临时停车优惠券" },
    couponParkingSpaceRechargeView: { eventid: "couponParkingSpaceRechargeView", eventLabel: "查看车位充值优惠券" },
    couponRoomView: { eventid: "couponRoomView", eventLabel: "查看会议室优惠券" },
    couponFieldView: { eventid: "couponFieldView", eventLabel: "查看场地优惠券" },
    couponStationView: { eventid: "couponStationView", eventLabel: "查看工位优惠券" },
    couponAdvertisingSpaceView: { eventid: "couponAdvertisingSpaceView", eventLabel: "查看广告位优惠券" },
    couponReceive: { eventid: "couponReceive", eventLabel: "优惠券领取" },

    questionnaireSurveyListBrowse: { eventid: "questionnaireSurveyListBrowse", eventLabel: "问卷列表浏览" },
    questionnaireSurveyView: { eventid: "questionnaireSurveyView", eventLabel: "问卷查看" },
    questionnaireSurveySearch: { eventid: "questionnaireSurveySearch", eventLabel: "问卷搜索" },
    submitQuestionnaireSurvey: { eventid: "submitQuestionnaireSurvey", eventLabel: "提交问卷" },

    marketCompanyRegistered: { eventid: "marketCompanyRegistered", eventLabel: "公司注册" },
    marketFiscalTaxationService: { eventid: "marketFiscalTaxationService", eventLabel: "财税服务" },
    marketLegalServices: { eventid: "marketLegalServices", eventLabel: "法律服务" },
    marketManpowerTraining: { eventid: "marketManpowerTraining", eventLabel: "人力培训" },
    marketITservices: { eventid: "marketITservices", eventLabel: "IT服务" },
    marketBrandCreativity: { eventid: "marketBrandCreativity", eventLabel: "品牌创意" },
    marketIntellPropertyRight: { eventid: "marketIntellPropertyRight", eventLabel: "知识产权" },
    marketOther: { eventid: "marketOther", eventLabel: "其他" },
    marketServiceTypeFiltering: { eventid: "marketServiceTypeFiltering", eventLabel: "服务类型筛选" },
    marketServiceCitySelection: { eventid: "marketServiceCitySelection", eventLabel: "服务城市筛选" },
    marketIntelligentAortFiltering: { eventid: "marketIntelligentAortFiltering", eventLabel: "智能排序筛选" },
    marketServiceConsulting: { eventid: "marketServiceConsulting", eventLabel: "服务机构咨询" },
    marketCollectionAervice: { eventid: "marketCollectionAervice", eventLabel: "服务机构收藏" },
    marketServiceApplication: { eventid: "marketServiceApplication", eventLabel: "服务机构申请" },
    marketQualificationView: { eventid: "marketQualificationView", eventLabel: "机构资质查看" },
    marketDetailShare: { eventid: "marketDetailShare", eventLabel: "机构详情分享" },
    marketDetailQQShare: { eventid: "marketDetailQQShare", eventLabel: "机构详情QQ分享" },
    marketDetailWeChatShare: { eventid: "marketDetailWeChatShare", eventLabel: "机构详情微信分享" },
    marketDetailWeiboShare: { eventid: "marketDetailWeiboShare", eventLabel: "机构详情微博分享" },
    marketDetailSpaceShare: { eventid: "marketDetailSpaceShare", eventLabel: "机构详情空间分享" },
    marketSearch: { eventid: "marketSearch", eventLabel: "服务机构搜索" },
    marketProductView: { eventid: "marketProductView", eventLabel: "服务产品查看" },

    productView: { eventid: "productView", eventLabel: "机构信息查看" },
    productCompanyRegistered: { eventid: "productCompanyRegistered", eventLabel: "公司注册类" },
    productFiscalTaxationService: { eventid: "productFiscalTaxationService", eventLabel: "财税服务类" },
    productLegalServices: { eventid: "productLegalServices", eventLabel: "法律服务类" },
    productManpowerTraining: { eventid: "productManpowerTraining", eventLabel: "人力培训类" },
    productITservices: { eventid: "productITservices", eventLabel: "IT服务类" },
    productBrandCreativity: { eventid: "productBrandCreativity", eventLabel: "品牌创意类" },
    productIntellectualPropertyRights: { eventid: "productIntellectualPropertyRights", eventLabel: "知识产权类" },
    productOther: { eventid: "productOther", eventLabel: "其他类" },
    productSearch: { eventid: "productSearch", eventLabel: "服务产品搜索" },
    productServiceTypeFiltering: { eventid: "productServiceTypeFiltering", eventLabel: "产品类型筛选" },
    productIntelAortFiltering: { eventid: "productIntelAortFiltering", eventLabel: "产品智能排序筛选" },
    productChargeType: { eventid: "productChargeType", eventLabel: "收费方式筛选" },
    productServiceConsulting: { eventid: "productServiceConsulting", eventLabel: "服务产品咨询" },
    productCollectionAervice: { eventid: "productCollectionAervice", eventLabel: "服务产品收藏" },
    productServiceApplication: { eventid: "productServiceApplication", eventLabel: "服务产品申请" },
    productDetailShare: { eventid: "productDetailShare", eventLabel: "产品详情分享" },
    productDetailQQShare: { eventid: "productDetailQQShare", eventLabel: "产品详情QQ分享" },
    productDetailWeChatShare: { eventid: "productDetailWeChatShare", eventLabel: "产品详情微信分享" },
    productDetailWeiboShare: { eventid: "productDetailWeiboShare", eventLabel: "产品详情微博分享" },
    productDetailSpaceShare: { eventid: "productDetailSpaceShare", eventLabel: "产品详情空间分享" },

    onShelfProductBrowse: { eventid: "onShelfProductBrowse", eventLabel: "上架产品浏览" },
    offShelfProductBrowse: { eventid: "offShelfProductBrowse", eventLabel: "下架产品浏览" },
    onShelfProduct: { eventid: "onShelfProduct", eventLabel: "服务产品上架" },
    offShelfProduct: { eventid: "offShelfProduct", eventLabel: "服务产品下架" },
    addProduct: { eventid: "addProduct", eventLabel: "服务产品发布" },

    marketApplyBrowse: { eventid: "marketApplyBrowse", eventLabel: "服务受理列表浏览" },
    viewAcceptanceMarketApply: { eventid: "viewAcceptanceMarketApply", eventLabel: "查看待受理服务" },
    viewProcessMarketApply: { eventid: "viewProcessMarketApply", eventLabel: "查看处理中服务" },
    viewCompletedMarketApply: { eventid: "viewCompletedMarketApply", eventLabel: "查看已完成服务" },
    viewReturnedMarketApply: { eventid: "viewReturnedMarketApply", eventLabel: "查看已退回服务" },
    marketApplyDetailView: { eventid: "marketApplyDetailView", eventLabel: "服务受理详情查看" },
    WorkOrderAcceptTrigger: { eventid: "acceptMarketApply", eventLabel: "服务受理工单受理" },
    WorkOrderFinishTrigger: { eventid: "finishMarketApply", eventLabel: "服务受理工单完成" },
    WorkOrderReturnTrigger: { eventid: "returnMarketApply", eventLabel: "服务受理工单退回" },
    consultMarketApply: { eventid: "consultMarketApply", eventLabel: "服务受理工单咨询" },

    serviceMeetingDetailView: { eventid: "serviceMeetingDetailView", eventLabel: "会议室详情查看" },
    serviceAdvertisingDetailView: { eventid: "serviceAdvertisingDetailView", eventLabel: "广告位详情查看" },
    serviceStationDetailView: { eventid: "serviceStationDetailView", eventLabel: "工位详情查看" },
    serviceSiteDetailView: { eventid: "serviceSiteDetailView", eventLabel: "场地详情查看" },

    serviceMeetingReservation: { eventid: "serviceMeetingReservation", eventLabel: "会议室预订" },
    serviceMeetingConsultation: { eventid: "serviceMeetingConsultation", eventLabel: "会议室咨询" },
    serviceMeetingCollection: { eventid: "serviceMeetingCollection", eventLabel: "会议室收藏" },
    serviceMeetingShare: { eventid: "serviceMeetingShare", eventLabel: "会议室分享" },
    serviceMeetingSbmitOrders: { eventid: "serviceMeetingSbmitOrders", eventLabel: "提交订单" },
    serviceMeetingQQShare: { eventid: "serviceMeetingQQShare", eventLabel: "QQ分享" },
    serviceMeetingWeChatShare: { eventid: "serviceMeetingWeChatShare", eventLabel: "微信分享" },
    serviceMeetingWeiboShare: { eventid: "serviceMeetingWeiboShare", eventLabel: "微博分享" },
    serviceMeetingSpaceShare: { eventid: "serviceMeetingSpaceShare", eventLabel: "空间分享" },

    serviceSiteReservation: { eventid: "serviceSiteReservation", eventLabel: "场地预订" },
    serviceSiteConsultation: { eventid: "serviceSiteConsultation", eventLabel: "场地咨询" },
    serviceSiteCollection: { eventid: "serviceSiteCollection", eventLabel: "场地收藏" },
    serviceSiteShare: { eventid: "serviceSiteShare", eventLabel: "场地分享" },
    serviceSiteSbmitOrders: { eventid: "serviceSiteSbmitOrders", eventLabel: "提交订单" },
    serviceSiteQQShare: { eventid: "serviceSiteQQShare", eventLabel: "QQ分享" },
    serviceSiteWeChatShare: { eventid: "serviceSiteWeChatShare", eventLabel: "微信分享" },
    serviceSiteWeiboShare: { eventid: "serviceSiteWeiboShare", eventLabel: "微博分享" },
    serviceSiteSpaceShare: { eventid: "serviceSiteSpaceShare", eventLabel: "空间分享" },

    serviceAdvertisingReservation: { eventid: "serviceAdvertisingReservation", eventLabel: "广告位预订" },
    serviceAdvertisingConsultation: { eventid: "serviceAdvertisingConsultation", eventLabel: "广告位咨询" },
    serviceAdvertisingCollection: { eventid: "serviceAdvertisingCollection", eventLabel: "广告位收藏" },
    serviceAdvertisingShare: { eventid: "serviceAdvertisingShare", eventLabel: "广告位分享" },
    serviceAdvertisingSbmitOrders: { eventid: "serviceAdvertisingSbmitOrders", eventLabel: "提交订单" },
    serviceAdvertisingQQShare: { eventid: "serviceAdvertisingQQShare", eventLabel: "QQ分享" },
    serviceAdvertisingWeChatShare: { eventid: "serviceAdvertisingWeChatShare", eventLabel: "微信分享" },
    serviceAdvertisingWeiboShare: { eventid: "serviceAdvertisingWeiboShare", eventLabel: "微博分享" },
    serviceAdvertisingSpaceShare: { eventid: "serviceAdvertisingSpaceShare", eventLabel: "空间分享" },

    serviceStationReservation: { eventid: "serviceStationReservation", eventLabel: "工位预订" },
    serviceStationConsultation: { eventid: "serviceStationConsultation", eventLabel: "工位咨询" },
    serviceStationCollection: { eventid: "serviceStationCollection", eventLabel: "工位收藏" },
    serviceStationShare: { eventid: "serviceStationShare", eventLabel: "工位分享" },
    serviceStationSbmitOrders: { eventid: "serviceStationSbmitOrders", eventLabel: "提交订单" },
    serviceStationQQShare: { eventid: "serviceStationQQShare", eventLabel: "QQ分享" },
    serviceStationWeChatShare: { eventid: "serviceStationWeChatShare", eventLabel: "微信分享" },
    serviceStationWeiboShare: { eventid: "serviceStationWeiboShare", eventLabel: "微博分享" },
    serviceStationSpaceShare: { eventid: "serviceStationSpaceShare", eventLabel: "空间分享" },

    verificationCodeLogin: { eventid: "verificationCodeLogin", eventLabel: "验证码登录" },
    accountPasswordLogin: { eventid: "accountPasswordLogin", eventLabel: "账号密码登录" },
    logout: { eventid: "logout", eventLabel: "退出登录" },
    forgotPassword: { eventid: "forgotPassword", eventLabel: "忘记密码" },
    userAgreementView: { eventid: "userAgreementView", eventLabel: "用户协议查看" },
    changePassword: { eventid: "changePassword", eventLabel: "修改密码" },

    userNameView: { eventid: "userNameView", eventLabel: "用户名查看" },
    myDynamicView: { eventid: "myDynamicView", eventLabel: "个人动态浏览" },
    myCircleView: { eventid: "myCircleView", eventLabel: "个人话题浏览" },
    myfansView: { eventid: "myfansView", eventLabel: "我的粉丝浏览" },
    myFollowView: { eventid: "myFollowView", eventLabel: "我关注的浏览" },
    uploadPicture: { eventid: "uploadPicture", eventLabel: "上传头像" },
    modificationPersonalData: { eventid: "modificationPersonalData", eventLabel: "修改个人资料" },
    enterpriseInformationUnbund: { eventid: "enterpriseInformationUnbund", eventLabel: "企业信息解绑" },
    authenticationInformationView: { eventid: "authenticationInformationView", eventLabel: "企业认证查看" },
    submitCertificationInformation: { eventid: "submitCertificationInformation", eventLabel: "企业认证提交" },

    integralTypeSwitch: { eventid: "integralTypeSwitch", eventLabel: "积分类型切换" },
    helpView: { eventid: "helpView", eventLabel: "帮助说明查看" },
    integralSignIn: { eventid: "integralSignIn", eventLabel: "积分签到" },
    intergralDetail: { eventid: "intergralDetail", eventLabel: "积分详情浏览" },
    integralRuleGuidelines: { eventid: "integralRuleGuidelines", eventLabel: "积分规则指引" },

    workOrderSearch: { eventid: "workOrderSearch", eventLabel: "工单搜索" },
    worksheetListBrowse: { eventid: "worksheetListBrowse", eventLabel: "工单列表浏览" },
    workOrderDetailView: { eventid: "workOrderDetailView", eventLabel: "查看工单详情" },
    cancelpendingworkorder: { eventid: "cancelpendingworkorder", eventLabel: "取消待受理工单" },
    evaluationRepairOrder: { eventid: "evaluationRepairOrder", eventLabel: "评价工单" },
    QrCodeAccessCard: { eventid: "QrCodeAccessCard", eventLabel: "二维门禁卡" },
    WorkOrderRepairCancelTrigger: { eventid: "repairCancelTrigger", eventLabel: "取消报修工单" },
    WorkOrderRepairContinueTrigger: { eventid: "continueRepairOrder", eventLabel: "继续报修工单" },
    WorkOrderRepairSuccessTrigger: { eventid: "successRepairOrder", eventLabel: "设为维修成功工单" },
    WorkOrderRepairFailTrigger: { eventid: "failRepairOrder", eventLabel: "设为维修失败工单" },

    viewAcceptanceWorkOrders: { eventid: "viewAcceptanceWorkOrders", eventLabel: "查看待受理工单" },
    viewProcessWorkOrders: { eventid: "viewProcessWorkOrders", eventLabel: "查看处理中工单" },
    viewCompletedWorkOrders: { eventid: "viewCompletedWorkOrders", eventLabel: "查看已完成工单" },
    viewEvaluationWorkOrders: { eventid: "viewEvaluationWorkOrders", eventLabel: "查看待评价工单" },
    viewCanceledWorkOrders: { eventid: "viewCanceledWorkOrders", eventLabel: "查看已取消工单" },
    viewReturnedWorkOrders: { eventid: "viewReturnedWorkOrders", eventLabel: "查看已退回工单" },

    serviceNotifications: { eventid: "serviceNotifications", eventLabel: "服务通知" },
    interactiveMessage: { eventid: "interactiveMessage", eventLabel: "互动消息" },
    parkPush: { eventid: "parkPush", eventLabel: "园区推送" },

    serviceNotificationListBrowse: { eventid: "serviceNotificationListBrowse", eventLabel: "服务通知列表浏览" },
    serviceNoticeDetailView: { eventid: "serviceNoticeDetailView", eventLabel: "服务通知详情查看" },
    serviceNotifMessagesAllRead: { eventid: "serviceNotifMessagesAllRead", eventLabel: "服务通知消息全部已读" },

    interactiveMessageBrowse: { eventid: "interactiveMessageBrowse", eventLabel: "互动消息浏览" },
    interactiveNewsDetailView: { eventid: "interactiveNewsDetailView", eventLabel: "互动消息详情查看" },
    interactiveMessagesAllRead: { eventid: "interactiveMessagesAllRead", eventLabel: "互动消息全部已读" },

    parkPushMessageBrowse: { eventid: "parkPushMessageBrowse", eventLabel: "园区推送消息浏览" },
    parkPushDetailView: { eventid: "parkPushDetailView", eventLabel: "园区推送详情查看" },
    parkPushMessagesSentAllRead: { eventid: "parkPushMessagesSentAllRead", eventLabel: "园区推送消息全部已读" },

    myVisitorAppReviewBrowse: { eventid: "myVisitorAppReviewBrowse", eventLabel: "预约审核浏览" },

    myVerificationDetailView: { eventid: "myVerificationDetailView", eventLabel: "查看预约审核详情" },
    myAppointmentApproval: { eventid: "myAppointmentApproval", eventLabel: "预约审核通过" },
    myAppointmentDenied: { eventid: "myAppointmentDenied", eventLabel: "预约审核不通过" },

    certificationAudit: { eventid: "certificationAudit", eventLabel: "认证审核" },
    managerBrowse: { eventid: "managerBrowse", eventLabel: "员工浏览" },

    detailAuditView: { eventid: "detailAuditView", eventLabel: "查看审核详情" },
    certificationApproval: { eventid: "certificationApproval", eventLabel: "认证审核通过" },
    certificationAuditFailed: { eventid: "certificationAuditFailed", eventLabel: "认证审核不通过" },

    changingManagerRoles: { eventid: "changingManagerRoles", eventLabel: "修改员工角色" },
    unbindManagerCertification: { eventid: "unbindManagerCertification", eventLabel: "解绑员工认证" },

    myOrderSearch: { eventid: "myOrderSearch", eventLabel: "订单搜索" },
    myOrderListBrowse: { eventid: "myOrderListBrowse", eventLabel: "订单列表浏览" },
    myOrderDetailView: { eventid: "myOrderDetailView", eventLabel: "查看订单详情" },
    cancelOrderPendingPayment: { eventid: "cancelOrderPendingPayment", eventLabel: "取消待支付订单" },
    cancelPendingOrder: { eventid: "cancelPendingOrder", eventLabel: "取消待审核订单" },
    inquiryHasCancelledOrder: { eventid: "inquiryHasCancelledOrder", eventLabel: "咨询已取消订单" },
    reorderCancelled: { eventid: "reorderCancelled", eventLabel: "重新预订已取消订单" },
    evaluatePendingOrders: { eventid: "evaluatePendingOrders", eventLabel: "评价待评价订单" },
    refundafter: { eventid: "refundafter", eventLabel: "退款售后" },

    paidOrderView: { eventid: "paidOrderView", eventLabel: "查看待支付订单" },
    auditOrderView: { eventid: "auditOrderView", eventLabel: "查看待审核订单" },
    usedOrderView: { eventid: "usedOrderView", eventLabel: "查看待使用订单" },
    evaluateOrderView: { eventid: "evaluateOrderView", eventLabel: "查看待评价订单" },
    cancelledOrderView: { eventid: "cancelledOrderView", eventLabel: "查看已取消订单" },

    applyRefund: { eventid: "applyRefund", eventLabel: "申请退款" },
    cancellationRefundApplication: { eventid: "cancellationRefundApplication", eventLabel: "取消退款申请" },

    myActivitiesBrowse: { eventid: "myActivitiesBrowse", eventLabel: "活动浏览" },

    cancelEventRegistration: { eventid: "cancelEventRegistration", eventLabel: "取消活动报名" },
    collectionActivities: { eventid: "collectionActivities", eventLabel: "活动收藏" },
    activitiesSignin: { eventid: "activitiesSignin", eventLabel: "活动签到" },
    modifyRegistrationInformation: { eventid: "modifyRegistrationInformation", eventLabel: "修改报名信息" },
    myActivityShare: { eventid: "myActivityShare", eventLabel: "活动分享" },
    myActivityComments: { eventid: "myActivityComments", eventLabel: "活动评论" },

    myActivityQQShare: { eventid: "myActivityQQShare", eventLabel: "QQ分享" },
    myActivityWeChatShare: { eventid: "myActivityWeChatShare", eventLabel: "微信分享" },
    myActivityWeiboShare: { eventid: "myActivityWeiboShare", eventLabel: "微博分享" },
    myActivitySpaceShare: { eventid: "myActivitySpaceShare", eventLabel: "空间分享" },

    myActivitySendComments: { eventid: "myActivitySendComments", eventLabel: "发送评论" },
    myActivityDeleteComment: { eventid: "myActivityDeleteComment", eventLabel: "删除评论" },
    myActivityReplyComments: { eventid: "myActivityReplyComments", eventLabel: "回复评论" },

    myCheckinListBrowse: { eventid: "myCheckinListBrowse", eventLabel: "入驻申请列表浏览" },
    myCheckinDetailView: { eventid: "myCheckinDetailView", eventLabel: "入驻申请详情查看" },

    myServiceOrgListBrowse: { eventid: "myServiceOrgListBrowse", eventLabel: "机构入驻列表浏览" },
    myServiceOrgDetailView: { eventid: "myServiceOrgDetailView", eventLabel: "机构入驻详情查看" },

    mySurveyListBrowse: { eventid: "mySurveyListBrowse", eventLabel: "我的问卷列表浏览" },
    mySurveyDetailView: { eventid: "mySurveyDetailView", eventLabel: "我的问卷详情查看" },
    mySurveySearch: { eventid: "mySurveySearch", eventLabel: "我的问卷搜索" },

    myFavoritesListBrowse: { eventid: "myFavoritesListBrowse", eventLabel: "收藏列表浏览" },
    myCollectionDetailView: { eventid: "myCollectionDetailView", eventLabel: "收藏详情查看" },
    myCollectSearch: { eventid: "myCollectSearch", eventLabel: "收藏搜索" },
    myCancelCollection: { eventid: "myCancelCollection", eventLabel: "取消收藏" },

    personalInformationEditing: { eventid: "personalInformationEditing", eventLabel: "个人信息编辑" },
    accountAndSecurity: { eventid: "accountAndSecurity", eventLabel: "账号与安全" },

    changeMobilePhone: { eventid: "changeMobilePhone", eventLabel: "换绑手机" },
    bindSocialAccounts: { eventid: "bindSocialAccounts", eventLabel: "绑定社交账号" },

    qqBind: { eventid: "qqBind", eventLabel: "绑定qq" },
    weChatBind: { eventid: "weChatBind", eventLabel: "绑定微信" },
    weiboBind: { eventid: "weiboBind", eventLabel: "绑定微博" },

    feedback: { eventid: "feedback", eventLabel: "意见反馈" },

    submitFeedback: { eventid: "submitFeedback", eventLabel: "提交意见反馈" },
    myFeedbackListBrowse: { eventid: "myFeedbackListBrowse", eventLabel: "我的反馈列表浏览" },
    myFeedbackDetailView: { eventid: "myFeedbackDetailView", eventLabel: "我的反馈详情查看" },

    newsNotification: { eventid: "newsNotification", eventLabel: "新消息通知" },

    messageReceivingSetting: { eventid: "messageReceivingSetting", eventLabel: "消息接收设置" },
    serviceNotifMessageReceiveSet: { eventid: "serviceNotifMessageReceiveSet", eventLabel: "服务通知消息接收设置" },
    parkPushMessageReceiveSet: { eventid: "parkPushMessageReceiveSet", eventLabel: "园区推送消息接收设置" },
    interactiveMessageReceiveSet: { eventid: "interactiveMessageReceiveSet", eventLabel: "互动消息消息接收设置" },

    aboutUs: { eventid: "aboutUs", eventLabel: "关于我们" },
    clearCache: { eventid: "clearCache", eventLabel: "清除缓存" },

    versionUpdate: { eventid: "versionUpdate", eventLabel: "版本更新" },
    recommendFriends: { eventid: "recommendFriends", eventLabel: "推荐给好友" },
    callCustomerService: { eventid: "callCustomerService", eventLabel: "拨打客服电话" },

    setingQQShare: { eventid: "setingQQShare", eventLabel: "QQ分享" },
    setingWeChatShare: { eventid: "setingWeChatShare", eventLabel: "微信分享" },
    setingWeiboShare: { eventid: "setingWeiboShare", eventLabel: "微博分享" },
    setingSpaceShare: { eventid: "setingSpaceShare", eventLabel: "空间分享" },
    parkHeadlineCollection: { eventid: "parkHeadlineCollection", eventLabel: "资讯收藏" },
    parkHeadlineReplyComments: { eventid: "parkHeadlineReplyComments", eventLabel: "资讯回复评论" },
    parkHeadlineDeleteComment: { eventid: "parkHeadlineDeleteComment", eventLabel: "资讯删除评论" },
    parkHeadlineSendComments: { eventid: "parkHeadlineSendComments", eventLabel: "资讯发送评论" },
    parkHeadPraise: { eventid: "parkHeadPraise", eventLabel: "资讯点赞" },
    parkHeadShare: { eventid: "parkHeadShare", eventLabel: "资讯分享" },
    parkHeadlineQQShare: { eventid: "parkHeadlineQQShare", eventLabel: "资讯QQ分享" },
    parkHeadlineWeChatShare: { eventid: "parkHeadlineWeChatShare", eventLabel: "资讯微信分享" },
    parkHeadlineWeiboShare: { eventid: "parkHeadlineWeiboShare", eventLabel: "资讯微博分享" },
    parkHeadlineSpaceShare: { eventid: "parkHeadlineSpaceShare", eventLabel: "资讯空间分享" }
};
